server:
   port: 8888

ami:
   username : user
   password : pwd
   enabled: true
   server : localhost

logging.level:
   com.africasys: DEBUG
   org.asteriskjava: INFO
   org.springframework: WARN

cluster:
    backend.topic: backend.topic
    asterisk.queue: asterisk.queue
    
broker:
    url: failover:tcp://localhost:61616
    login: login
    pwd: pwd
    jms.enabled: true
