ami:
   username : user
   password : pwd
   enabled: true
   server : localhost

logging.level:
   com.africasys: DEBUG
   org.springframework: INFO

cluster:
    backend.topic:backend.topic
    asterisk.queue:asterisk.queue
    
broker:
    url: failover:tcp://localhost:61616
    login: 
    pwd: 
    jms.enabled: true
